openapi: 3.0.0
info:
  title: myapi
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /users:
    get:
      summary: the get
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../common/models/modelx.v1.yaml
              examples: {}
            application/xml:
              schema:
                $ref: ../common/models/modelx.v1.yaml
              examples:
                example-1: {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../common/models/modely.v1.yaml
components:
  schemas: {}
